#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  basic:
    external:
      name: net_basic

services:
  cliDigiBank:
    container_name: cliDigiBank
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=info
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.DigiBank.papernet.com:8051
      - CORE_PEER_LOCALMSPID=DigiBankMSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/DigiBank.papernet.com/users/Admin@DigiBank.papernet.com/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../../../../organization/digibank:/opt/gopath/src/github.com/
        - ./../../../../../../fabric-paper/config:/opt/gopath/src/github.com/hyperledger/fabric/peer/config/
        - ./../../../../../../fabric-paper/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
    networks:
        - basic
    #depends_on:
    #  - orderer.papernet.com
    #  - peer0.DigiBank.papernet.com
    #  - couchdb
