# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# ---------------------------------------------------------------------------
# cryptogen generate --config=./crypto-config.yaml
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------

OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer digibank
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: MagnetoCorp.com
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # DigiBank
  # ---------------------------------------------------------------------------
  - Name: MagnetoCorp
    Domain: MagnetoCorp.com
    EnableNodeOUs: true
    Template:
      Count: 3
    Users:
      Count: 1